name: "Fix PHP Code Styling"

on:
  push:
    branches: [ main ]
    paths:
      - '**.php'
  pull_request:
    branches: [ main ]
    paths:
      - '**.php'

permissions:
  contents: write
  pull-requests: write

jobs:
  php-code-styling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Fix PHP code style issues
        uses: aglipanci/laravel-pint-action@2.5

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: |
            Fix PHP code styling issues
            
            - Fix PHP code styling issues
          branch: php-style-fixes
          title: Fix PHP Code Styling
          labels: code-style
          auto-merge: true
          delete-branch: true
